In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('../data/mmALL_073119_csv.csv')

In [4]:
df.head()

,id,country,ccode,year,region,protest,protestnumber,startday,startmonth,startyear,...,protesterdemand4,stateresponse1,stateresponse2,stateresponse3,stateresponse4,stateresponse5,stateresponse6,stateresponse7,sources,notes
0,201990001,Canada,20,1990,North America,1,1,15.0,1.0,1990.0,...,NaN,ignore,NaN,NaN,NaN,NaN,NaN,NaN,1. Great Canadian train journeys into history;...,Canada s railway passenger system was finally...
1,201990002,Canada,20,1990,North America,1,2,25.0,6.0,1990.0,...,NaN,ignore,NaN,NaN,NaN,NaN,NaN,NaN,1. Autonomy s Cry Revived in Quebec The New Yo...,protestors were only identified as young peop...
2,201990003,Canada,20,1990,North America,1,3,1.0,7.0,1990.0,...,NaN,ignore,NaN,NaN,NaN,NaN,NaN,NaN,1. Quebec protest after Queen calls for unity ...,"THE Queen, after calling on Canadians to rema..."
3,201990004,Canada,20,1990,North America,1,4,12.0,7.0,1990.0,...,NaN,accomodation,NaN,NaN,NaN,NaN,NaN,NaN,1. Indians Gather as Siege Intensifies; Armed ...,Canada s federal government has agreed to acq...
4,201990005,Canada,20,1990,North America,1,5,14.0,8.0,1990.0,...,NaN,crowd dispersal,arrests,accomodation,NaN,NaN,NaN,NaN,1. Dozens hurt in Mohawk blockade protest The ...,Protests were directed against the state due t...

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16363 entries, 0 to 16362
Data columns (total 31 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     16363 non-null  int64
 1   country                16363 non-null  object
 2   ccode                  16363 non-null  int64
 3   year                   16363 non-null  int64
 4   region                 16363 non-null  object
 5   protest                16363 non-null  int64
 6   protestnumber          16363 non-null  int64
 7   startday               14514 non-null  float64
 8   startmonth             14514 non-null  float64
 9   startyear              14514 non-null  float64
 10  endday                 14514 non-null  float64
 11  endmonth               14514 non-null  float64
 12  endyear                14514 non-null  float64
 13  protesterviolence      15033 non-null  float64
 14  location               14493 non-null  object
 15  participants_category  9160 non-null   object
 16  participants           15021 non-null  object
 17  protesteridentity      13959 non-null  object
 18  protesterdemand1       14503 non-null  object
 19  protesterdemand2       2676 non-null   object
 20  protesterdemand3       316 non-null    object
 21  protesterdemand4       896 non-null    object
 22  stateresponse1         14483 non-null  object
 23  stateresponse2         2716 non-null   object
 24  stateresponse3         850 non-null    object
 25  stateresponse4         230 non-null    object
 26  stateresponse5         926 non-null    object
 27  stateresponse6         16 non-null     object
 28  stateresponse7         920 non-null    object
 29  sources                14510 non-null  object
 30  notes                  14468 non-null  object
dtypes: float64(7), int64(5), object(19)
memory usage: 3.9+ MB