In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression, LogisticRegression, LassoCV, RidgeCV, Lasso, Ridge
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor 
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.ensemble import BaggingClassifier, BaggingRegressor
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.ensemble import GradientBoostingClassifier, AdaBoostClassifier, AdaBoostRegressor, VotingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV, train_test_split, StratifiedKFold

from sklearn.svm import LinearSVC, SVC, SVR

In [3]:
df = pd.read_csv('../data/clean_data.csv')

In [4]:
df_model = df

In [5]:
df_model.head()

,country,year,region,protestnumber,startday,startmonth,startyear,endday,endmonth,endyear,...,labor wage dispute,land farm issue,police brutality,"political behavior, process","price increases, tax policy",removal of politician,social restrictions,startdate,enddate,duration
0,Canada,1990,North America,1,15.0,1.0,1990.0,15.0,1.0,1990.0,...,1,0,0,1,0,0,0,1990-01-15,1990-01-15,0 days 00:00:00.000000000
1,Canada,1990,North America,2,25.0,6.0,1990.0,25.0,6.0,1990.0,...,0,0,0,1,0,0,0,1990-06-25,1990-06-25,0 days 00:00:00.000000000
2,Canada,1990,North America,3,1.0,7.0,1990.0,1.0,7.0,1990.0,...,0,0,0,1,0,0,0,1990-07-01,1990-07-01,0 days 00:00:00.000000000
3,Canada,1990,North America,4,12.0,7.0,1990.0,6.0,9.0,1990.0,...,0,1,0,0,0,0,0,1990-07-12,1990-09-06,56 days 00:00:00.000000000
4,Canada,1990,North America,5,14.0,8.0,1990.0,15.0,8.0,1990.0,...,0,0,0,1,0,0,0,1990-08-14,1990-08-15,1 days 00:00:00.000000000

### Dropped Unnamed Column

In [10]:
#df_model.drop(columns = 'Unnamed: 0', inplace = True)

In [11]:
df_model.head()

,country,year,region,protestnumber,startday,startmonth,startyear,endday,endmonth,endyear,...,labor wage dispute,land farm issue,police brutality,"political behavior, process","price increases, tax policy",removal of politician,social restrictions,startdate,enddate,duration
0,Canada,1990,North America,1,15.0,1.0,1990.0,15.0,1.0,1990.0,...,1,0,0,1,0,0,0,1990-01-15,1990-01-15,0 days 00:00:00.000000000
1,Canada,1990,North America,2,25.0,6.0,1990.0,25.0,6.0,1990.0,...,0,0,0,1,0,0,0,1990-06-25,1990-06-25,0 days 00:00:00.000000000
2,Canada,1990,North America,3,1.0,7.0,1990.0,1.0,7.0,1990.0,...,0,0,0,1,0,0,0,1990-07-01,1990-07-01,0 days 00:00:00.000000000
3,Canada,1990,North America,4,12.0,7.0,1990.0,6.0,9.0,1990.0,...,0,1,0,0,0,0,0,1990-07-12,1990-09-06,56 days 00:00:00.000000000
4,Canada,1990,North America,5,14.0,8.0,1990.0,15.0,8.0,1990.0,...,0,0,0,1,0,0,0,1990-08-14,1990-08-15,1 days 00:00:00.000000000

In [12]:
df_model.columns

Index(['country', 'year', 'region', 'protestnumber', 'startday', 'startmonth',
       'startyear', 'endday', 'endmonth', 'endyear', 'protesterviolence',
       'participants', 'notes', 'stateresponse', 'labor wage dispute',
       'land farm issue', 'police brutality', 'political behavior, process',
       'price increases, tax policy', 'removal of politician',
       'social restrictions', 'startdate', 'enddate', 'duration'],
      dtype='object')

In [29]:
X.columns

Index(['year', 'protestnumber', 'startday', 'startmonth', 'startyear',
       'endday', 'endmonth', 'endyear', 'protesterviolence', 'participants',
       'labor wage dispute', 'land farm issue', 'police brutality',
       'political behavior, process', 'price increases, tax policy',
       'removal of politician', 'social restrictions'],
      dtype='object')

country, region, startdate , end date duration --- not included
- startdate - end date didnt merge (didnt want to mess it up) 

not including for now just to get a better sense of which models to focus on

## Baseline

In [14]:
df_model['stateresponse'].value_counts(normalize = True)

ignore             0.530883
crowd dispersal    0.174036
arrests            0.101285
accomodation       0.069918
killings           0.052992
beatings           0.042490
shootings          0.028396
Name: stateresponse, dtype: float64

In [15]:
# need to beat 53%

###  Define X and y variables

In [16]:
X = df_model._get_numeric_data()

In [17]:
y = df_model['stateresponse']

In [18]:
# might have to remap for modeling purposes

#### Train Test Split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

#### Scale

In [20]:
ss = StandardScaler()
X_train_sc = ss.fit_transform(X_train)
X_test_sc = ss.transform(X_test)

### Basic Models

In [21]:
abc = AdaBoostClassifier()
bc = BaggingClassifier()
rfc = RandomForestClassifier()
lr = LogisticRegression()
knc = KNeighborsClassifier()
svc = SVC()
dtc = DecisionTreeClassifier()
classification_models = [abc, bc, rfc, lr, knc, svc, dtc]
for model in classification_models:
    print(model)
    model.fit(X_train_sc, y_train)
    print(model.score(X_train_sc, y_train))
    print(model.score(X_test_sc, y_test))

AdaBoostClassifier()
0.5900506678949793
0.575849682232661
BaggingClassifier()
0.9825886688162138
0.5413097540757115
RandomForestClassifier()
0.9998157531091663
0.5772312793589389
LogisticRegression()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

0.591524643021649
0.5788891959104725
KNeighborsClassifier()
0.6428374021188392
0.5092567007460624
SVC()
0.5988023952095808
0.5813760707377729
DecisionTreeClassifier()
0.9998157531091663
0.43658469190384086

In [22]:
# DT / KN / RF / Bagging overfit - bad test scores - can work on gridsearching later

### Dummy Country?

In [23]:
df_model['country'].value_counts()

United Kingdom           547
France                   526
Ireland                  428
Germany                  360
Kenya                    348
                        ...
Bhutan                     2
Cape Verde                 2
Serbia and Montenegro      2
Qatar                      1
South Sudan                1
Name: country, Length: 166, dtype: int64

In [24]:
pd.set_option('display.max_rows', None)
df_model['country'].value_counts().to_frame()

                          country
United Kingdom                547
France                        526
Ireland                       428
Germany                       360
Kenya                         348
South Korea                   340
Bangladesh                    336
Venezuela                     314
Greece                        308
China                         263
Thailand                      246
Namibia                       225
Brazil                        220
Romania                       215
Nepal                         206
India                         203
Russia                        192
Pakistan                      172
South Africa                  171
Italy                         163
Peru                          162
Kyrgyzstan                    160
Yemen                         157
Chile                         156
Spain                         155
Nigeria                       150
Ecuador                       149
Ukraine                       148
Indonesia                     147
Taiwan                        147
Malaysia                      146
Mexico                        145
Yugoslavia                    137
Colombia                      134
Bolivia                       130
Turkey                        126
Cyprus                        125
Azerbaijan                    125
Bulgaria                      122
Egypt                         121
Poland                        117
Iran                          116
Argentina                     111
Haiti                         111
Madagascar                    110
Ivory Coast                   110
Zimbabwe                      109
Guatemala                     107
Moldova                       107
Niger                         106
Iraq                          104
Honduras                      104
Armenia                       103
Burundi                        98
Cuba                           97
Swaziland                      94
Zambia                         94
Togo                           93
Guinea                         88
Nicaragua                      86
Latvia                         85
Kazakhstan                     81
Mauritania                     81
Comoros                        80
Macedonia                      79
Mozambique                     75
Congo Kinshasa                 73
Myanmar                        72
Sri Lanka                      71
Dominican Republic             69
Belarus                        68
Uruguay                        68
Albania                        67
Hungary                        67
Burkina Faso                   65
Paraguay                       65
Ghana                          64
Liberia                        64
Philippines                    62
Central African Republic       61
USSR                           60
Lebanon                        58
Algeria                        58
Uganda                         58
Georgia                        57
Japan                          56
Cameroon                       56
Malawi                         52
Cambodia                       52
Sudan                          52
Suriname                       51
El Salvador                    50
Canada                         50
Panama                         49
Mongolia                       49
Estonia                        48
Mali                           46
Bahrain                        46
Senegal                        44
Jordan                         44
Slovak Republic                43
Tunisia                        42
Belgium                        41
Kuwait                         40
Afghanistan                    38
Papua New Guinea               38
Ethiopia                       37
Tanzania                       37
Uzbekistan                     36
Costa Rica                     36
Guyana                         35
Morocco                        35
Lithuania                      35
Congo Brazzaville              35
Gabon                          34
Benin                          33
Lesotho                        32
Sierra Leone                   32
Tajikistan                     32
Botswana                       32
Bosnia                         31
Portugal                       31
Jamaica                        28
Guinea-Bissau                  27
Oman                           26
Serbia                         24
Croatia                        23
Czech Republic                 23
Libya                          23
Angola                         23
Somalia                        22
Saudi Arabia                   21
Slovenia                       21
Vietnam                        19
Kosovo                         19
Chad                           17
Syria                          17
Gambia                         16
Sweden                         16
Singapore                      14
Mauritius                      13
Austria                        13
Finland                        12
Montenegro                     12
Timor Leste                    12
Netherlands                    12
Germany East                   11
Denmark                        10
Djibouti                       10
Rwanda                         10
North Korea                     8
Norway                          6
Switzerland                     5
Equatorial Guinea               4
Czechoslovakia                  4
Turkmenistan                    4
United Arab Emirate             3
Luxembourg                      3
Eritrea                         3
Laos                            2
Germany West                    2
Bhutan                          2
Cape Verde                      2
Serbia and Montenegro           2
Qatar                           1
South Sudan                     1

In [25]:
# focus on countries wih over a certain number of protest

In [26]:
df_model['country'].value_counts().loc[lambda x: x>100] 
# create filter for columns where a country has more than 100 protests

United Kingdom    547
France            526
Ireland           428
Germany           360
Kenya             348
South Korea       340
Bangladesh        336
Venezuela         314
Greece            308
China             263
Thailand          246
Namibia           225
Brazil            220
Romania           215
Nepal             206
India             203
Russia            192
Pakistan          172
South Africa      171
Italy             163
Peru              162
Kyrgyzstan        160
Yemen             157
Chile             156
Spain             155
Nigeria           150
Ecuador           149
Ukraine           148
Indonesia         147
Taiwan            147
Malaysia          146
Mexico            145
Yugoslavia        137
Colombia          134
Bolivia           130
Turkey            126
Cyprus            125
Azerbaijan        125
Bulgaria          122
Egypt             121
Poland            117
Iran              116
Argentina         111
Haiti             111
Madagascar        110
Ivory Coast       110
Zimbabwe          109
Guatemala         107
Moldova           107
Niger             106
Iraq              104
Honduras          104
Armenia           103
Name: country, dtype: int64

## Lasso / Ridge Logistic Regression

In [27]:
ridge_model = Ridge(alpha=10)

In [28]:
ridge_model.fit(X_train_sc, y_train)

ValueError: could not convert string to float: 'arrests'